image: danvancam/s3-pusher:v1


pipelines:
  default:
    - step:
        script:
          - sh /app/configure.sh $S3_ID $S3_SECRET
          - sh /app/pusher.sh /opt/atlassian/pipelines/agent/build $S3_BUCKET
